app-nginx-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
app-nginx-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
app-nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
app-nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
app-nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
app-nginx-1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
app-nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
app-nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
app-nginx-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
app-postgres-1  | The files belonging to this database system will be owned by user "postgres".
app-postgres-1  | This user must also own the server process.
app-postgres-1  | 
app-postgres-1  | The database cluster will be initialized with locale "en_US.utf8".
app-postgres-1  | The default database encoding has accordingly been set to "UTF8".
app-postgres-1  | The default text search configuration will be set to "english".
app-postgres-1  | 
app-postgres-1  | Data page checksums are disabled.
app-postgres-1  | 
app-postgres-1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
app-postgres-1  | creating subdirectories ... ok
app-postgres-1  | selecting dynamic shared memory implementation ... posix
app-postgres-1  | selecting default max_connections ... 100
app-postgres-1  | selecting default shared_buffers ... 128MB
app-postgres-1  | selecting default time zone ... Etc/UTC
app-postgres-1  | creating configuration files ... ok
app-golang-instance-1  | 2024/02/15 18:04:10 Erro ao conectar com banco de dados: dial tcp 172.20.0.2:5432: connect: connection refused
app-golang-instance-1  | panic: Erro ao conectar com banco de dados: dial tcp 172.20.0.2:5432: connect: connection refused
app-golang-instance-1  | 
app-golang-instance-1  | goroutine 1 [running]:
app-golang-instance-1  | log.Panic({0x4000497f38?, 0x8?, 0x4000497f28?})
app-golang-instance-1  | 	/usr/local/go/src/log/log.go:385 +0x68
app-golang-instance-1  | golang-first-api-rest/database.ConectaComBancoDeDados()
app-golang-instance-1  | 	/app/database/db.go:19 +0x138
app-golang-instance-1  | main.main()
app-golang-instance-1  | 	/app/main.go:9 +0x20
app-golang-instance-1  | 2024/02/15 18:04:11 Erro ao conectar com banco de dados: dial tcp 172.20.0.2:5432: connect: connection refused
app-golang-instance-1  | panic: Erro ao conectar com banco de dados: dial tcp 172.20.0.2:5432: connect: connection refused
app-golang-instance-1  | 
app-golang-instance-1  | goroutine 1 [running]:
app-golang-instance-1  | log.Panic({0x400050ff38?, 0x8?, 0x400050ff28?})
app-golang-instance-1  | 	/usr/local/go/src/log/log.go:385 +0x68
app-golang-instance-1  | golang-first-api-rest/database.ConectaComBancoDeDados()
app-golang-instance-1  | 	/app/database/db.go:19 +0x138
app-golang-instance-1  | main.main()
app-golang-instance-1  | 	/app/main.go:9 +0x20
app-golang-instance-2-1  | 2024/02/15 18:04:10 Erro ao conectar com banco de dados: dial tcp 172.20.0.2:5432: connect: connection refused
app-golang-instance-2-1  | panic: Erro ao conectar com banco de dados: dial tcp 172.20.0.2:5432: connect: connection refused
app-golang-instance-2-1  | 
app-golang-instance-2-1  | goroutine 1 [running]:
app-golang-instance-2-1  | log.Panic({0x400050ff38?, 0x8?, 0x400050ff28?})
app-golang-instance-2-1  | 	/usr/local/go/src/log/log.go:385 +0x68
app-golang-instance-2-1  | golang-first-api-rest/database.ConectaComBancoDeDados()
app-golang-instance-2-1  | 	/app/database/db.go:19 +0x138
app-golang-instance-2-1  | main.main()
app-golang-instance-2-1  | 	/app/main.go:9 +0x20
app-golang-instance-2-1  | 2024/02/15 18:04:11 Erro ao conectar com banco de dados: dial tcp 172.20.0.2:5432: connect: connection refused
app-golang-instance-2-1  | panic: Erro ao conectar com banco de dados: dial tcp 172.20.0.2:5432: connect: connection refused
app-golang-instance-2-1  | 
app-golang-instance-2-1  | goroutine 1 [running]:
app-golang-instance-2-1  | log.Panic({0x400048ff38?, 0x8?, 0x400048ff28?})
app-golang-instance-2-1  | 	/usr/local/go/src/log/log.go:385 +0x68
app-golang-instance-2-1  | golang-first-api-rest/database.ConectaComBancoDeDados()
app-golang-instance-2-1  | 	/app/database/db.go:19 +0x138
app-golang-instance-2-1  | main.main()
app-golang-instance-2-1  | 	/app/main.go:9 +0x20
